### ISSUE TITLE
Reading on JS graphs for landing page

### ISSUE THREAD

**Issue by charlottebrf** [charlottebrf/DoctorsWhoCode#10]
https://d3js.org

**Comment by sohbaker** [comment]
Continue reading on options: 
http://www.chartjs.org/docs/
http://www.highcharts.com/products/highcharts
http://chartkick.com

**Comment by sohbaker** [comment]
https://github.com/ankane/chartkick

![aiming to use this bar chart but change fields](https://cloud.githubusercontent.com/assets/18250108/19866256/b2f3d32c-9f9f-11e6-8b1a-9077c8e02169.png)

**Comment by melikecode** [comment]
Closed. Thanks @ShivsBee for picking a super awesome chart function! The simplicity of the one you picked made life soooo much easier!
