### ISSUE TITLE
Develop a weekly activity summary

### ISSUE THREAD

**Issue by melikecode** [charlottebrf/DoctorsWhoCode#20]
- I want to view the time I spent on each activity by week 
	• Is a "week" based on calendar, last 7 days, or other period?)
	• Convert time spent to hours, or leave in minutes?
	• Add a helpful text summary?

**Comment by melikecode** [comment]
Weekly summary is done in minutes with no text summary. 

Ideas for improving are most welcome!

**Comment by charlottebrf** [comment]
Think weekly sounds good! @ajh146 nice job
