### ISSUE TITLE
Edit code so that work vs not work chart renders in a different colour to activities

### ISSUE THREAD

**Issue by sohbaker** [charlottebrf/DoctorsWhoCode#45]
Currently both charts are blue, think it would be better for one to be a different colour

**Comment by melikecode** [comment]
Awesome idea!

**Comment by sohbaker** [comment]
thanks for the colors:"green" for the work chart!

chartkick seems limited in terms of rendering each bar line in a different colour https://github.com/ankane/chartkick/issues/77
