### ISSUE TITLE
Add Back button at bottom of week, month, targets pages

### ISSUE THREAD

**Issue by melikecode** [charlottebrf/DoctorsWhoCode#48]
For ease of use on mobiles. 

Add to week, month, target .erb files, at the bottom of the page somewhere:

<a href="href="javascript:history.back()"><button class="btn btn-sm btn-primary">GO BACK</button></a>

...note you may want to put some padding or margin at the top so that it's not too close to all the main stuff on the page

**Comment by sohbaker** [comment]
added the go back button but the link is broken

**Comment by melikecode** [comment]
What are you seeing or not seeing?

**Comment by melikecode** [comment]
Ahh oops i think I forgot to include the script information see below

http://www.w3schools.com/jsref/met_his_back.asp

**Comment by sohbaker** [comment]
fixed it now, it didn't like the href after a ref
