### ISSUE TITLE
not_work label on work graph

### ISSUE THREAD

**Issue by sohbaker** [charlottebrf/DoctorsWhoCode#54]
It was basically a teeny tiny thing on the homepage.erb, line 147<label class="radio-inline"><input type="radio" name="task_type" value=**"not_work"** required="required">Not Work</label>. We've only seen this now because we're displaying a chart.

I've now changed it but taking out the underscore, which also gets rid of the underscore from the chart label, **buttt** this now affects the bar chart as it considers that to be a new value... will we be able to consolidate that before tomorrow or should I leave it as it was?

**Comment by sohbaker** [comment]
![screen shot 2016-11-13 at 17 04 06](https://cloud.githubusercontent.com/assets/18250108/20247383/26b8c6fc-a9cb-11e6-9d8b-97d6d1261fd2.png)

**Comment by melikecode** [comment]
I see two options:
1. Go into the JSON file and do a find and replace to change not_work to "not work" 
2. Change "not_work" and "not work" in JSON and .erb files to "leisure"

**Comment by sohbaker** [comment]
changed all to leisure
