### ISSUE TITLE
Top and bottom padding for body

### ISSUE THREAD

**Issue by melikecode** [charlottebrf/DoctorsWhoCode#55]
Not sure if it's just my machine but it seems the top and bottom body padding is really really small. If you have the same, do you want to put that in with your other CSS changes?

**Comment by charlottebrf** [comment]
@ajh146 @ShivsBee has this been corrected? I noticed during presentation on the redirect to the login that there needed more padding. Happy to do some CSS.

**Comment by sohbaker** [comment]
Hi,

I wasn't too sure what happened there. When I looked again on my machine after we'd finished it was fine and all the css was showing. 😕

Happy for you to have a look at it. We took the padding off the top as on heroku it was adding a white bar across the top. 

Siobhan

**Comment by melikecode** [comment]
I think you fixed this already! I had raised this over the weekend I think, and you updated it before today's session, so I think it's fine now.
